services:
  site:
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - NUXT_HOST=0.0.0.0
    ports:
      - "3000:3000"
    build:
      dockerfile: Dockerfile
      context: .
  db:
    image: ghcr.io/tursodatabase/libsql-server:latest
    env_file:
      - .env
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "5001:5001"
    # environment:
    #   - SQLD_NODE=primary
    volumes:
      - ./sqld:/var/lib/sqld
    environment:
      - 'JWT=${JWT}'
      - 'SQLD_AUTH_JWT_KEY=${SQLD_AUTH_JWT_KEY}'
